### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1
### Verbo GET – listar um
GET http://localhost:8000/produto/10 HTTP/1.1
### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json
{
    "nome" : "Pastel de Carne",
    "descricao" : "Carne Moída, Ovos, etc.",
    "foto" : " ",
    "valor_unitario" : 8.99
}
### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json
{
    "nome" : "Pastel de Frango",
    "descricao" : "Frango desfiado, Molho de Tomate, etc.",
    "foto" : " ",
    "valor_unitario" : 8.99
}
### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1