### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
### Verbo GET – listar todos
curl -X 'GET' \
    'http://localhost:8000/cliente/' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'
### Verbo GET – listar um
GET http://localhost:8000/cliente/10 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

curl -X 'GET' \
    'http://localhost:8000/cliente/10' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

curl -X 'GET' \
    'http://127.0.0.1:8000/cliente/' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'

content-type: application/json
{
    "nome" : "Abc da Silva",
    "cpf" : "01923874656",
    "telefone" : "49988234567",
    "compra_fiado" : "sim",
    "dia_fiado" : "12",
    "senha" : "bolinhas"
}
### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/2 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

curl -X 'GET' \
    'http://localhost:8000/cliente/2' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'

content-type: application/json
{
    "nome" : "Bolinhas dos Testes",
    "cpf" : "12345678909",
    "telefone" : "49898989",
    "compra_fiado" : "não",
    "dia_fiado" : "25",
    "senha" : "naosei"
}
### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/3 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
### Verbo GET – listar todos
curl -X 'GET' \
    'http://localhost:8000/cliente/3' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'
